#!/usr/bin/env python3

'''
    Delete map script
'''

import os
import sys

try:
    import pexpect
except ImportError:
    print('Required library "pexpect" not exists. Install with pip and try again')
    sys.exit(1)

# Define command to request new token
_COMMAND_ = 'python3 ./src/map_client.py "%(map_proxy)s" "%(token)s" -r "%(roomName)s"'

# Message used by authentication client when asking for a password
_TIMEOUT_FOR_MESSAGE_ = 15

# Get required arguments
try:
    map_proxy, token, roomName = sys.argv[1:]
except ValueError:
    print('Command arguments: {} <map_proxy> <token> <roomName>'.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)

# Compose command
final_command = _COMMAND_ % {
    'map_proxy': map_proxy,
    'token': token,
    'roomName': roomName
}

# Run command
proc = pexpect.spawn(final_command, echo=False)
proc.expect([pexpect.EOF], timeout=_TIMEOUT_FOR_MESSAGE_)
# Exit
sys.exit(0)
