#!/usr/bin/env python3

'''
    Run Map Server Script
'''

import os
import sys

def main():
    try:
        import pexpect
    except ImportError:
        print('Required library "pexpect" not exists. Install with pip and try again')
        sys.exit(1)

    # Define command to request new token
    _COMMAND_ = 'python3 ./src/auth_server.py --Ice.Config=./src/auth_server.config'

    # Run command
    proc = pexpect.spawn(_COMMAND_, echo=False)
    print(proc.readline().decode())
    proc.expect([pexpect.EOF],timeout=None)

    #Show command output and exit
    print(proc.before.decode().strip())

try:
    main()
except KeyboardInterrupt:
    pass

sys.exit(0)
