#!/usr/bin/env python3

import os
import sys

try:
    import pexpect
except ImportError:
    print('Required library "pexpect" not exists. Install with pip and try again')
    sys.exit(1)

# Define command to request new token
_COMMAND_ = 'python3 ./src/icegauntlet2/dungeon_client.py "%(game_proxy)s"'

# Message used by authentication client when asking for a password
_NUMBER_MESSAGE_ = 'Cuantos mapas quieres jugar:'
_TIMEOUT_FOR_MESSAGE_ = 15

# Get required arguments
try:
    game_proxy = sys.argv[1]
except ValueError:
    print('Command arguments: {} <game_proxy>'.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)

# Compose command
final_command = _COMMAND_ % {
    'game_proxy': game_proxy
}

# Run command
proc = pexpect.spawn(final_command, echo=False)
# Wait for client to ask for password
found = proc.expect(
    [_NUMBER_MESSAGE_, pexpect.TIMEOUT, pexpect.EOF], timeout=_TIMEOUT_FOR_MESSAGE_
)
if found == 0:
    # Enter password
    proc.sendline('1')
    # Wait end
    proc.expect([pexpect.EOF])
else:
    # Client execution failed
    print('ERROR: authentication command does not ask for password after {} seconds'.format(
        _TIMEOUT_FOR_MESSAGE_
    ))
    sys.exit(1)

# Show command output and exit
print(proc.before.decode().strip())
sys.exit(0)
