#!/usr/bin/env python3

import os
import sys

try:
    import pexpect
except ImportError:
    print('Required library "pexpect" not exists. Install with pip and try again')
    sys.exit(1)

# Define command to request new token
_COMMAND_ = 'cat gameProxy.txt'

# Message used by authentication client when asking for a password
_TIMEOUT_FOR_MESSAGE_ = 15

# Run command
proc = pexpect.spawn(_COMMAND_, echo=False)
proc.expect([pexpect.EOF], timeout=_TIMEOUT_FOR_MESSAGE_)

#Show command output and exit
print(proc.before.decode().strip())
sys.exit(0)
