#!/usr/bin/env python3

'''
    Run Map Server Script
'''

import os
import sys

def main():
    try:
        import pexpect
    except ImportError:
        print('Required library "pexpect" not exists. Install with pip and try again')
        sys.exit(1)

    # Define command to request new token
    _COMMAND_ = 'python3 ./src/map_server.py --Ice.Config=./src/map_server.config "%(auth_proxy)s"'

    # Get required arguments
    try:
        auth_proxy = sys.argv[1]
    except ValueError:
        print('Command arguments: {} <auth_proxy>'.format(
            os.path.basename(sys.argv[0]))
        )
        sys.exit(1)

    # Compose command
    final_command = _COMMAND_ % {
        'auth_proxy': auth_proxy
    }

    # Run command
    proc = pexpect.spawn(final_command, echo=False)
    print(proc.readline().decode())
    proc.expect([pexpect.EOF],timeout=None)

    #Show command output and exit
    print(proc.before.decode().strip())

try:
    main()
except KeyboardInterrupt:
    pass

sys.exit(0)
