#!/usr/bin/env python3

import os
import sys
def main():
    try:
        import pexpect
    except ImportError:
        print('Required library "pexpect" not exists. Install with pip and try again')
        sys.exit(1)

    # Define command to request new token
    _COMMAND_ = 'python3 ./src/MapServer.py --Ice.Config=./src/MapServer.config "%(auth_proxy)s"'

    # Get required arguments
    try:
        auth_proxy = sys.argv[1]
    except ValueError:
        print('Command arguments: {} <auth_proxy>'.format(
            os.path.basename(sys.argv[0]))
        )
        sys.exit(1)

    # Compose command
    final_command = _COMMAND_ % {
        'auth_proxy': auth_proxy
    }

    # Run command
    proc = pexpect.spawn(final_command, echo=False)
    proc.expect([pexpect.EOF])

    #Show command output and exit
    print(proc.before.decode().strip())

try:
    main()
except KeyboardInterrupt:
    pass

sys.exit(0)
